name: Run JMA AMeDAS scraper

on:
  schedule:
    - cron: '0 16 * * *' # 01:00 JST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: '1'
    steps:
      - name: Sparse Checkout (excluding csv/)
        run: |
          git init
          git remote add origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git config core.sparseCheckout true
          echo "/*" > .git/info/sparse-checkout
          echo "!csv/" >> .git/info/sparse-checkout
          git pull origin main

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python run_jma_amedas.py

      - name: Commit and push new CSVs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "dlxiii"
          git config --global user.email "tokyowangyulong@gmail.com"

          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          git add --sparse csv/
          git commit -m "Auto commit AMeDAS CSV for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin HEAD:main
